# -*- coding: utf-8 -*-
"""app_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3vGlQP9WuWyMJUf0_7EBQiYc1AJi_Wl
"""

from flask import Flask, render_template, request
import numpy as np
import pickle

app = Flask(__name__)
filename = 'SVM_model.pkl'
model = pickle.load(open(filename, 'rb'))

@app.route('/')
def index():
  return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
        math_score = request.form.get("math_score")
        reading_score = request.form.get("reading_score")
        writing_score = request.form.get("writing_score")
        features = [
            float(math_score),
            float(reading_score),
            float(writing_score)]
        prediction = model.predict([features])[0]
        if prediction == 1:
          prediction = "group A"
        if prediction == 2:
          prediction == "group B"
        if prediction == 3:
          prediction == "group C"
        if prediction == 4:
          prediction == "group D"
        if prediction == 5:
            prediction = "group E"
        return render_template("index.html", prediction=prediction)

if __name__ == '__main__':
    app.run(debug=True)